global:
  # How frequently to scrape targets by default.
  scrape_interval: 1s

# A list of scrape configurations.
scrape_configs:
  - job_name: 'blackbox-icmp'
    metrics_path: /probe
    params:
      module: [icmp]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - 192.168.1.30
        - 192.168.1.3
        - 192.168.1.201
        - 192.168.1.202
        - 192.168.1.203
        - 192.168.1.204
        - 192.168.1.205
        - 192.168.1.206
        - 192.168.1.207
        - 192.168.1.208
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115  # The blackbox exporter's real hostname:port.
  - job_name: 'blackbox_exporter'  # collect blackbox exporter's operational metrics.
    static_configs:
      - targets: ['blackbox:9115']


