services:
  # !! WARNING: !!
  # If using linuxserver/mariadb, you will need to add
  # skip-log-bin to mysqld and disable all log_bin options
  db:
    image: mariadb
    restart: always
    networks:
      - zoneminder
    volumes:
      - ./zm/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=zm
    env_file:
      - ./.env

  zoneminder:
    image: ghcr.io/zoneminder-containers/zoneminder-base:latest
    restart: always
    stop_grace_period: 45s
    depends_on:
      - db
    ports:
      - 80:80
      - "40001-40008:40001-40008"
    networks:
      - zoneminder
    volumes:
      # /data contains events and images
      - /var/nfs/zm-data/data:/data
      - ./zm/config:/config
      - ./zm/log:/log
      - ./html/live.html:/var/www/html/live.html
      - ./html/small.html:/var/www/html/small.html
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 1000000000
    env_file:
      - ./.env
#    environment:
#      - ZM_SERVER_HOST=zoneminder1


networks:
  zoneminder:
