version: 0.14

mqtt:
  enabled: false
  host: 192.168.1.22:1883

cameras:
  mpros:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.208:554/Streaming/Channels/101
          roles:
            - detect
      hwaccel_args: preset-vaapi
    detect:
      enabled: true
      #width: 1920
      #height: 1080
    webui_url: test
  pisw:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.201:554/Streaming/Channels/101
          roles:
            - detect
      hwaccel_args: preset-vaapi
    detect:
      enabled: true
      #width: 1280
      #height: 720
  porta:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.202:554/Streaming/Channels/101
          roles:
            - detect
      hwaccel_args: preset-vaapi
    detect:
      enabled: true
      #width: 1280
      #height: 720
  voreia-eisodos:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.205:554/Streaming/Channels/101
          roles:
            - detect
      hwaccel_args: preset-vaapi
    detect:
      enabled: true
      width: 1280
      height: 720
  deuteri-porta:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.203:554/Streaming/Channels/101
          roles:
            - detect
      hwaccel_args: preset-vaapi
    detect:
      enabled: true
      #width: 1280
      #height: 720
  peuko-garage:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.207:554/Streaming/Channels/101
          roles:
            - detect
      hwaccel_args: preset-vaapi
    detect:
      enabled: true
      #width: 1280
      #height: 720
  anatolika:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.206:554/Streaming/Channels/101
          roles:
            - detect
      hwaccel_args: preset-vaapi
    detect:
      enabled: true
      #width: 1280
      #height: 720
  varka:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.204:554/Streaming/Channels/101
          roles:
            - detect
      hwaccel_args: preset-vaapi
    detect:
      enabled: true
      #width: 1280
      #height: 720

go2rtc:
  streams:
    mpros:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.208:554/Streaming/Channels/101
    pisw:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.201:554/Streaming/Channels/101
    porta:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.202:554/Streaming/Channels/101
    voreia-eisodos:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.205:554/Streaming/Channels/101
    deuteri-porta:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.203:554/Streaming/Channels/101
    peuko-garage:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.207:554/Streaming/Channels/101
    anatolika:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.206:554/Streaming/Channels/101
    varka:
      - rtsp://{FRIGATE_RTSP_USER}:{FRIGATE_RTSP_PASSWORD}@192.168.1.204:554/Streaming/Channels/101
  webrtc:
    candidates:
      - 192.168.1.18:8555
      - stun:8555

record:
  enabled: true
  retain:
    days: 30
    mode: all

tls:
  enabled: false
camera_groups:
  test:
    order: 1
    icon: LuAlignCenterHorizontal
    cameras:
      - anatolika
      - deuteri-porta
      - mpros
      - peuko-garage
      - pisw
      - porta
      - varka
      - voreia-eisodos

detectors:
  ov:
    type: openvino
    device: CPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

motion:
  enabled: True
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 5
  # Optional: The percentage of the image used to detect lightning or other substantial changes where motion detection
  #           needs to recalibrate. (default: shown below)
  # Increasing this value will make motion detection more likely to consider lightning or ir mode changes as valid motion.
  # Decreasing this value will make motion detection more likely to ignore large amounts of motion such as a person approaching
  # a doorbell camera.
  lightning_threshold: 0.8
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: shown below)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 10 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 10
